"""An automatic notification and the stop hook's counters (owner's Q1, 2026-09-24;
PLAN S11; task 173).

The stop hook lets a turn with open gates end when the session's counters say it was
a chat reply: no write and fewer than five tool calls since the last prompt. The
chat-log hook reset those counters on EVERY prompt — also on a harness notification,
which is not the user's prompt and can land in the middle of a turn: measured on a
live session on 2026-10-10, a background command's `<task-notification>` took the
counters from `tools=20 writes=20` to `0 0` between two tool calls of one turn, so a
stop right after it was released with every gate open (task 088's finding Q1).

The owner's rule: "the stop hook's counters are no longer reset by an automatic
notification; the one exception: a turn started by a notification may exit if it made
zero writes."

These tests run the three REAL hooks as subprocesses, in the order the events happen:
`chat-log-hook` for a prompt, `state-echo-hook` for a tool call, `stop-hook` for a
stop. The rule is about an order of events; one hook alone cannot show it.

What the two hooks keep for it are two one-line files beside the session's `counters`:
`turn_end` (the tool count at the last stop the stop hook let through, and a nonce
made for that stop) and `notif_start` (the write count when a notification started a
turn, and the nonce of the mark it was taken from). A baseline counts only beside the
mark with ITS nonce — so one written late, after a user's prompt removed the mark or
after a later stop replaced it, is a dead letter whatever the order of the two hooks
(post-D6 run 1: a lock with a time limit had left a window). They are files of
their own, not keys of `counters`, since impl panel round 1 (opus, codex-high,
codex-medium): a key is set by copying the whole counters file and renaming the copy
over it, so a notification's hook that overlapped a tool call's hook could rename a
stale copy over that call's increment — and the write it lost was the one the stop
hook needed to see.
"""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

from tests._bashcheck import bash_or_skip
from tests.test_batch_close_guard import G, NOTE, ProjectFixture, checked
from tests.test_batch_close_guard import SESSION as BATCH_SESSION

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = REPO_ROOT / "plugins" / "playbook" / "scripts"
SID = "pid-notif-turn"

NOTIFICATIONS = (
    "<task-notification>\n<task-id>b1</task-id>\n<status>completed</status>\n</task-notification>",
    "[SYSTEM NOTIFICATION - NOT USER INPUT]\nThis is an automated background-task event.\n"
    "<task-notification>\n<task-id>b1</task-id>\n</task-notification>",
)
USER_COMMAND_ECHOES = (
    "<command-name>/playbook:work</command-name>\n<command-args>12</command-args>",
    "<local-command-caveat>Caveat: the messages below were generated by the user while "
    "running local commands.</local-command-caveat>",
)


class _Session(unittest.TestCase):
    """A project with one active task that has an open gate, and one session."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.project = Path(self._tmp.name) / "proj"
        task_dir = self.project / ".agent" / "tasks" / "001-x"
        task_dir.mkdir(parents=True)
        self.task_file = task_dir / "task.md"
        self.task_file.write_text(
            "# 001 - x\n\n## Status\nin_progress\n\n## Work Plan\n- [ ] a gate that is open\n",
            encoding="utf-8")
        self.session_dir = self.project / ".agent" / "sessions" / SID
        self.session_dir.mkdir(parents=True)
        (self.session_dir / "current_state").write_text("001\n", encoding="utf-8")
        self.counters_file = self.session_dir / "counters"
        self.turn_end = self.session_dir / "turn_end"
        self.notif_start = self.session_dir / "notif_start"
        self.prompt_gen = self.session_dir / "prompt_gen"
        # The stop hook asks the process chain whether the agent that stops is the
        # session's own. What a real chain holds depends on where the suite runs (CI:
        # no agent; a developer's session: one; a reviewer's sandbox: one or two), so
        # every hook here walks a fixture instead: a /proc with no agent in it.
        self.proc_root = Path(self._tmp.name) / "proc-no-agent"
        (self.proc_root / "self").mkdir(parents=True)

    def _nested_proc_root(self):
        """A /proc in which the process that starts the hooks (this test) is an agent
        whose PARENT is an agent too — the chain a nested `claude -p` leaves."""
        root = Path(self._tmp.name) / "proc-nested"
        (root / "self").mkdir(parents=True, exist_ok=True)
        for pid, parent in ((os.getpid(), 4242), (4242, 1)):
            d = root / str(pid)
            d.mkdir(exist_ok=True)
            (d / "status").write_text(f"Name:\tclaude\nState:\tS (sleeping)\nPPid:\t{parent}\n", encoding="utf-8")
            (d / "cmdline").write_bytes(b"claude\0-p\0do the thing\0")
        return root

    def _hook(self, name, payload, proc_root=None):
        env = dict(os.environ)
        env["PLAYBOOK_SESSION_ID"] = SID
        env["HOME"] = self._tmp.name
        env["PLAYBOOK_PROC_ROOT"] = str(proc_root or self.proc_root)
        for k in ("BASH_ENV", "PLAYBOOK_ROLE", "PLAYBOOK_EVAL_CONFIG"):
            env.pop(k, None)
        return subprocess.run(
            [bash_or_skip(), str(SCRIPTS / name)], cwd=self.project, env=env, text=True,
            input=json.dumps(payload), capture_output=True, timeout=60)

    # -- the events, as the harness sends them ---------------------------------------
    def prompt(self, text=None):
        if text is None:
            # each one different: the hook drops a message identical to the previous
            # one in the same second as a duplicate, before it resets anything
            self._n = getattr(self, "_n", 0) + 1
            text = f"a plain user prompt, number {self._n}"
        r = self._hook("chat-log-hook", {"prompt": text})
        self.assertEqual(r.returncode, 0, r.stderr)
        return r

    def tools(self, *names):
        for name in names:
            r = self._hook("state-echo-hook", {"tool_name": name, "tool_input": {"command": "true"}})
            self.assertEqual(r.returncode, 0, r.stderr)

    def stop(self, active=False, proc_root=None):
        return self._hook("stop-hook", {"stop_hook_active": active}, proc_root=proc_root)

    def counters(self) -> "dict[str, str]":
        if not self.counters_file.exists():
            return {}
        return dict(line.split("=", 1) for line in
                    self.counters_file.read_text(encoding="utf-8").splitlines() if "=" in line)

    def counts(self):
        c = self.counters()
        return int(c["tools"]), int(c["writes"])

    def a_turn_that_ended(self, writes=2):
        """A user's turn with `writes` writes that the stop hook let end: blocked once
        (open gate, real activity), then let through by its one-shot valve."""
        self.prompt()
        self.tools(*["Bash"] * writes)
        self.assertEqual(self.stop().returncode, 2)
        self.assertEqual(self.stop(active=True).returncode, 0)


class ANotificationDoesNotResetTheCounters(_Session):
    def test_an_automatic_notification_leaves_the_counts_as_they_were(self):
        for text in NOTIFICATIONS:
            with self.subTest(text[:24]):
                self.prompt()
                self.tools("Read", "Read", "Bash", "Read", "Bash")
                self.assertEqual(self.counts(), (5, 2))
                self.prompt(text)
                self.assertEqual(self.counts(), (5, 2),
                                 "a notification wiped the work count of the turn it landed in")

    def test_it_keeps_the_gate_fields_too(self):
        self.prompt()
        self.tools("Bash")
        with open(self.counters_file, "a", encoding="utf-8") as f:
            f.write("gate_x=1\n")
        self.prompt(NOTIFICATIONS[0])
        self.assertEqual(self.counters().get("gate_x"), "1")

    def test_the_echo_of_a_command_the_user_ran_still_resets(self):
        # `<command-name>` and `<local-command-caveat>` are skipped from the LOG like a
        # notification, but they are the user's act — a slash command, a `!` command —
        # and start a fresh count like any prompt of theirs.
        for text in USER_COMMAND_ECHOES:
            with self.subTest(text[:24]):
                self.prompt()
                self.tools("Read", "Bash", "Bash")
                self.prompt(text)
                self.assertEqual(self.counts(), (0, 0))

    def test_control_a_user_prompt_resets(self):
        self.prompt()
        self.tools("Read", "Bash", "Bash")
        self.prompt("and now something else")
        self.assertEqual(self.counts(), (0, 0))

    def test_with_no_counters_file_a_notification_creates_none(self):
        self.assertFalse(self.counters_file.exists())
        self.prompt(NOTIFICATIONS[0])
        self.assertFalse(self.counters_file.exists())


class AStopAfterANotification(_Session):
    def test_work_then_a_notification_in_the_middle_of_the_turn_then_a_stop_is_blocked(self):
        # What was measured live: the turn had worked, the notification landed between
        # two of its tool calls, and the stop that followed was released.
        self.prompt()
        self.tools("Bash", "Bash", "Read")
        self.prompt(NOTIFICATIONS[0])
        self.tools("Read")
        r = self.stop()
        self.assertEqual(r.returncode, 2, "released with a gate open and two writes in the turn")
        self.assertIn("BLOCKED: 1 unchecked gate(s)", r.stderr)

    def test_a_turn_a_notification_started_may_end_if_it_made_no_write(self):
        # The owner's exception. No tool-count limit in it: six read-only calls.
        self.a_turn_that_ended()
        self.prompt(NOTIFICATIONS[0])
        self.tools(*["Read"] * 6)
        r = self.stop()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_and_with_no_tool_call_at_all(self):
        self.a_turn_that_ended()
        self.prompt(NOTIFICATIONS[1])
        self.assertEqual(self.stop().returncode, 0)

    def test_one_write_in_that_turn_and_the_stop_is_blocked(self):
        for write in ("Bash", "Edit", "Write", "MultiEdit", "NotebookEdit"):
            with self.subTest(write):
                self.a_turn_that_ended()
                self.prompt(NOTIFICATIONS[0])
                self.tools("Read", write)
                self.assertEqual(self.stop().returncode, 2)

    def test_a_second_notification_during_that_turn_does_not_move_the_baseline(self):
        self.a_turn_that_ended()
        self.prompt(NOTIFICATIONS[0])
        self.tools("Read", "Bash")                  # the turn has written …
        self.prompt(NOTIFICATIONS[0])               # … and another notification lands in it
        self.tools("Read")
        self.assertEqual(self.stop().returncode, 2,
                         "the second notification was taken for the start of a turn")

    def test_two_notifications_before_any_tool_call_are_one_start(self):
        self.a_turn_that_ended()
        self.prompt(NOTIFICATIONS[0])
        self.prompt(NOTIFICATIONS[1])
        self.tools("Read")
        self.assertEqual(self.stop().returncode, 0)

    def test_each_turn_a_notification_starts_is_counted_from_its_own_start(self):
        self.a_turn_that_ended()
        self.prompt(NOTIFICATIONS[0])
        self.tools("Bash")
        self.assertEqual(self.stop().returncode, 2)             # it wrote
        self.assertEqual(self.stop(active=True).returncode, 0)  # … and ended by the valve
        self.prompt(NOTIFICATIONS[0])                           # the next one starts clean
        self.tools("Read")
        self.assertEqual(self.stop().returncode, 0)

    def test_a_user_prompt_ends_what_the_notification_began(self):
        # prompt → a reply with no tool call ends (the old bypass) → a notification
        # starts a turn at zero writes → the USER speaks → six read-only calls → stop.
        # Were the notification's baseline (0) still there, this would be released.
        self.prompt()
        self.assertEqual(self.stop().returncode, 0)
        self.prompt(NOTIFICATIONS[0])
        self.prompt("now do the real thing")
        self.tools(*["Read"] * 6)
        self.assertEqual(self.stop().returncode, 2)

    def test_a_stop_that_was_blocked_is_not_the_end_of_a_turn(self):
        self.prompt()
        self.tools("Bash", "Bash")
        self.assertEqual(self.stop().returncode, 2)
        self.assertFalse(self.turn_end.exists())
        self.prompt(NOTIFICATIONS[0])                # the turn goes on after the block
        self.assertFalse(self.notif_start.exists())
        self.assertEqual(self.stop().returncode, 2)

    def test_a_notification_right_after_a_user_prompt_is_not_a_start(self):
        # A reply with no tool call ends (mark: 0 tools). The USER speaks — and a
        # notification lands in their turn before its first tool call, when the tool
        # count is 0 again. The user's prompt must have taken the old mark away, or
        # this turn would pass for one a notification started.
        self.prompt()
        self.assertEqual(self.stop().returncode, 0)
        self.assertTrue(self.turn_end.exists())
        self.prompt("now do the real thing")
        self.assertFalse(self.turn_end.exists())
        self.prompt(NOTIFICATIONS[0])
        self.assertFalse(self.notif_start.exists())
        self.tools(*["Read"] * 6)
        self.assertEqual(self.stop().returncode, 2)

    def test_a_baseline_that_is_not_a_number_releases_nothing(self):
        for junk in ("abc", "", "-0", "0x0", "9" * 30, "$(touch pwned)"):
            with self.subTest(junk):
                self.counters_file.write_text("tools=9\nwrites=0\n", encoding="utf-8")
                self.turn_end.write_text("9 none-1\n", encoding="utf-8")
                self.notif_start.write_text(f"{junk} none-1\n", encoding="utf-8")
                self.assertEqual(self.stop().returncode, 2)
        self.turn_end.write_text("9 none-1\n", encoding="utf-8")
        self.notif_start.write_text("0 none-1\n", encoding="utf-8")   # control: a plain 0 does release
        self.assertEqual(self.stop().returncode, 0)

    def test_a_baseline_counts_only_beside_the_mark_it_was_taken_from(self):
        # writes=0 and nine tool calls: only the notification rule could release this
        def stop_with(turn_end, notif_start, prompt_gen=None):
            self.counters_file.write_text("tools=9\nwrites=0\n", encoding="utf-8")
            for path, text in ((self.turn_end, turn_end), (self.notif_start, notif_start),
                               (self.prompt_gen, prompt_gen)):
                if text is None:
                    path.unlink(missing_ok=True)
                else:
                    path.write_text(text, encoding="utf-8")
            return self.stop().returncode

        # a nonce begins with the prompt generation it was made in: `none` while the
        # session has seen no prompt of the user's, else the word in `prompt_gen`
        self.assertEqual(stop_with("9 none-A\n", "0 none-A\n"), 0)                       # control
        self.assertEqual(stop_with("9 g7-A\n", "0 g7-A\n", prompt_gen="0 g7\n"), 0)       # control
        for name, turn_end, notif_start, prompt_gen in (
                ("the mark is gone (a user's prompt removed it)", None, "0 none-A\n", None),
                ("the mark is a later stop's", "9 none-B\n", "0 none-A\n", None),
                ("the mark is of an older prompt generation", "9 g7-A\n", "0 g7-A\n", "0 g8\n"),
                ("the mark was made before any prompt, and there has been one since", "9 none-A\n", "0 none-A\n", "0 g8\n"),
                ("the baseline has no nonce", "9 none-A\n", "0\n", None),
                ("the mark has no nonce", "9\n", "0 none-A\n", None),
                ("neither has one", "9\n", "0\n", None),
                ("a third word on the baseline", "9 none-A\n", "0 none-A x\n", None),
                ("a nonce that is not a plain word", "9 $(touch pwned)\n", "0 $(touch pwned)\n", None),
                ("a nonce of 65 characters", "9 none-" + "a" * 60 + "\n", "0 none-" + "a" * 60 + "\n", None)):
            with self.subTest(name):
                self.assertEqual(stop_with(turn_end, notif_start, prompt_gen), 2)
        self.assertFalse((self.project / "pwned").exists())

    def test_each_stop_let_through_makes_a_new_nonce(self):
        seen = set()
        for _ in range(3):
            self.prompt()
            self.assertEqual(self.stop().returncode, 0)
            number, nonce = self.turn_end.read_text(encoding="utf-8").split()
            self.assertEqual(number, "0")
            self.assertRegex(nonce, r"^[A-Za-z0-9-]{8,64}$")
            # … and it begins with the generation of the prompt that turn answered
            self.assertEqual(nonce.split("-")[0], self.prompt_gen.read_text(encoding="utf-8").split()[1])
            seen.add(nonce)
        self.assertEqual(len(seen), 3)
        self.assertFalse((self.project / "pwned").exists())

    def test_every_tool_that_edits_a_file_is_a_write(self):
        # "Zero writes" is the hook's own count. It counted Edit, Write and Bash; a
        # MultiEdit or a NotebookEdit was a tool call but not a write, so a turn whose
        # only act was one of them read as a chat reply and was released (task 173:
        # the owner's exception rests on that count, so it has to count them).
        for edit in ("MultiEdit", "NotebookEdit"):
            with self.subTest(edit):
                self.prompt()
                self.tools(edit)
                self.assertEqual(self.counts(), (1, 1))
                self.assertEqual(self.stop().returncode, 2)

    def test_control_the_chat_reply_bypass_is_unchanged(self):
        self.prompt()
        self.tools("Read", "Read", "Read", "Read")
        self.assertEqual(self.stop().returncode, 0)             # no write, four calls
        self.prompt()
        self.tools("Read", "Read", "Read", "Read", "Read")
        self.assertEqual(self.stop().returncode, 2)             # five


class TheStopHookMarksOnlyAStopItLetThrough(_Session):
    """The mark the notification rule reads is written when the hook exits 0, and the
    hook's own verdict — its exit status, its message — comes out as before."""

    def _mark(self):
        """The tool count the mark holds (its first word; the second is its nonce)."""
        return self.turn_end.read_text(encoding="utf-8").split()[0] if self.turn_end.exists() else None

    def test_a_blocked_stop_leaves_no_mark_and_says_what_it_said(self):
        self.prompt()
        self.tools("Bash", "Read", "Bash")
        r = self.stop()
        self.assertEqual(r.returncode, 2)
        self.assertIn("BLOCKED: 1 unchecked gate(s) in task 001.", r.stderr)
        self.assertIn("First unchecked: a gate that is open", r.stderr)
        self.assertIsNone(self._mark())

    def test_each_way_a_stop_is_let_through_leaves_the_mark(self):
        def valve():
            self.assertEqual(self.stop().returncode, 2)
            return self.stop(active=True)

        def all_gates_done():
            self.task_file.write_text(self.task_file.read_text(encoding="utf-8").replace("- [ ]", "- [x]"),
                                      encoding="utf-8")
            return self.stop()

        def blocked_status():
            self.task_file.write_text(self.task_file.read_text(encoding="utf-8").replace(
                "## Status\nin_progress", "## Status\nblocked"), encoding="utf-8")
            return self.stop()

        def no_active_task():
            (self.session_dir / "current_state").unlink()
            return self.stop()

        for way in (valve, all_gates_done, blocked_status, no_active_task):
            with self.subTest(way.__name__):
                self.setUp()
                self.prompt()
                self.tools("Bash", "Read", "Bash")
                r = way()
                self.assertEqual(r.returncode, 0, r.stderr)
                self.assertEqual(self._mark(), "3", "the mark is the tool count at that stop")
                self.assertEqual(self.counts(), (3, 2))

    def test_the_chat_reply_bypass_leaves_it_too(self):
        self.prompt()
        self.tools("Read")
        self.assertEqual(self.stop().returncode, 0)
        self.assertEqual(self._mark(), "1")

    def test_with_no_counters_file_nothing_is_written(self):
        self.assertEqual(self.stop().returncode, 2)             # no file = work assumed
        self.assertFalse(self.counters_file.exists())
        # … and a stop that IS let through does not create one either (the first
        # version of this test only drove the blocked stop, which marks nothing
        # anyway — a break that let the mark create the file passed it)
        self.assertEqual(self.stop(active=True).returncode, 0)
        self.assertFalse(self.counters_file.exists())
        (self.session_dir / "current_state").unlink()
        self.assertEqual(self.stop().returncode, 0)             # no active task
        self.assertFalse(self.counters_file.exists())
        self.assertFalse(self.turn_end.exists())


class TheCountersFileIsNeverRewrittenByTheRule(_Session):
    """Impl panel round 1 (opus, codex-high, codex-medium). A counter key is set by
    copying the whole file and renaming the copy over it; done by a hook that overlaps
    a tool call's hook, that rename can put a stale copy over the call's increment.
    Neither of the rule's two writers touches the counters file, and the notification
    hook reads it ONCE — one consistent picture of `tools` and `writes`."""

    def _identity(self):
        st = os.stat(self.counters_file)
        return st.st_ino, self.counters_file.read_bytes()

    def test_a_stop_let_through_and_a_notification_leave_the_file_as_it_was(self):
        self.prompt()
        self.tools("Bash", "Read")
        before = self._identity()
        self.assertEqual(self.stop().returncode, 2)
        self.assertEqual(self.stop(active=True).returncode, 0)       # writes the mark
        self.assertEqual(self._identity(), before, "the stop hook rewrote the counters file")
        self.prompt(NOTIFICATIONS[0])                                # notes the baseline
        self.assertTrue(self.notif_start.exists())
        self.assertEqual(self._identity(), before, "the notification's hook rewrote the counters file")

    def _shims(self, bump_after_read):
        """`cat` and `sed` first on PATH: they count each read OF THE COUNTERS FILE and,
        after the Nth, do what a tool call's hook does — `tools` then `writes`, +1 each."""
        import shutil
        bindir = Path(self._tmp.name) / "shims"
        bindir.mkdir()
        count = Path(self._tmp.name) / "reads"
        for tool in ("cat", "sed"):
            real = shutil.which(tool)
            (bindir / tool).write_text(f"""#!/bin/bash
"{real}" "$@"; rc=$?
for a in "$@"; do
    if [ "$a" = "{self.counters_file}" ]; then
        n=$(( $("{shutil.which('cat')}" "{count}" 2>/dev/null || echo 0) + 1 )); echo "$n" > "{count}"
        if [ "$n" -eq {bump_after_read} ]; then
            "{shutil.which('sed')}" -i -E 's/^tools=(.*)$/tools=3/; s/^writes=(.*)$/writes=3/' "{self.counters_file}"
        fi
    fi
done
exit $rc
""", encoding="utf-8")
            (bindir / tool).chmod(0o755)
        return bindir, count

    def _notify_through_shims(self, bindir):
        env = dict(os.environ, PLAYBOOK_SESSION_ID=SID, HOME=self._tmp.name,
                   PATH=f"{bindir}{os.pathsep}{os.environ['PATH']}")
        for k in ("BASH_ENV", "PLAYBOOK_ROLE", "PLAYBOOK_EVAL_CONFIG"):
            env.pop(k, None)
        r = subprocess.run([bash_or_skip(), str(SCRIPTS / "chat-log-hook")], cwd=self.project, env=env,
                           text=True, capture_output=True, timeout=60,
                           input=json.dumps({"prompt": NOTIFICATIONS[0]}))
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_a_write_that_lands_while_the_notification_is_read_still_holds_the_stop(self):
        # tools=2 writes=2 at the mark; a tool call's hook lands during the
        # notification's hook (3 and 3). Whichever read it lands after, the stop that
        # follows must be held: the turn has written since the notification.
        for nth in (1, 2, 3):
            with self.subTest(after_read=nth):
                self.setUp()
                self.a_turn_that_ended()
                self.assertEqual(self.counts(), (2, 2))
                bindir, count = self._shims(nth)
                self._notify_through_shims(bindir)
                reads = int(count.read_text(encoding="utf-8")) if count.exists() else 0
                self.assertEqual(reads, 1, "the notification's hook read the counters file more than once")
                self.assertEqual(self.counts(), (3, 3) if nth == 1 else (2, 2))
                if nth == 1:
                    self.assertEqual(self.stop().returncode, 2,
                                     "a write landed during the notification and the stop was released")


class ANotificationAndAUserPromptAtOnce(_Session):
    """Impl panel round 2 (codex-high, codex-medium), then post-D6 run 1. The
    notification's hook reads the mark, and only later writes its baseline; a USER
    prompt whose hook ran in between reset the counters and removed both marks — and
    the baseline written after it then stood in the user's own turn, which could end
    on it. Round 2's answer was a lock with a 5 s limit; the single judge pointed at
    the limit (a reset that stopped waiting ran unlocked, and the baseline was
    published after it). No ordering is relied on now: the baseline carries the nonce
    of the mark it was taken from, and the stop hook honours it only beside that very
    mark — which the user's prompt removed."""

    def _notify_while_the_user_speaks(self, shimmed):
        """Run the notification's hook with `shimmed` (an external command it calls)
        replaced by a shim that, on its first call for a file of this session, runs
        the USER's prompt hook to its END (bounded at 8 s) before doing its own work.
        The other hook is detached from the shim's output: the notification's hook
        reads the shim through a pipe and would wait for anything still holding it."""
        import shutil
        bindir = Path(self._tmp.name) / "shims"
        bindir.mkdir()
        done = Path(self._tmp.name) / "user-prompt-done"
        payload = Path(self._tmp.name) / "user-prompt.json"
        payload.write_text(json.dumps({"prompt": "the user speaks while the notification is handled"}),
                           encoding="utf-8")
        hook = SCRIPTS / "chat-log-hook"
        (bindir / shimmed).write_text(f"""#!/bin/bash
for a in "$@"; do
    case "$a" in "{self.session_dir}"/*)
        if [ ! -e "{done}.started" ]; then
            : > "{done}.started"
            ( PATH="$PB_REAL_PATH" "{bash_or_skip()}" "{hook}" < "{payload}"; : > "{done}" ) 204>&- >/dev/null 2>&1 &
            for _ in $(seq 1 160); do [ -e "{done}" ] && break; "$PB_REAL_SLEEP" 0.05; done
        fi ;;
    esac
done
exec "{shutil.which(shimmed)}" "$@"
""", encoding="utf-8")
        (bindir / shimmed).chmod(0o755)
        env = dict(os.environ, PLAYBOOK_SESSION_ID=SID, HOME=self._tmp.name, PB_REAL_PATH=os.environ["PATH"],
                   PB_REAL_SLEEP=shutil.which("sleep"), PLAYBOOK_PROC_ROOT=str(self.proc_root),
                   PATH=f"{bindir}{os.pathsep}{os.environ['PATH']}")
        for k in ("BASH_ENV", "PLAYBOOK_ROLE", "PLAYBOOK_EVAL_CONFIG"):
            env.pop(k, None)
        r = subprocess.run([bash_or_skip(), str(hook)], cwd=self.project, env=env, text=True,
                           capture_output=True, timeout=60, input=json.dumps({"prompt": NOTIFICATIONS[0]}))
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertTrue(done.exists(), "the user's prompt hook never finished")
        self.assertIn("the user speaks while the notification is handled",
                      (self.project / ".agent" / "chat_log.md").read_text(encoding="utf-8"))

    def _a_turn_that_ended_without_a_write(self):
        # mark: 0 tools — a later baseline of 0 would release any read-only turn
        self.prompt()
        self.assertEqual(self.stop().returncode, 0)
        self.assertTrue(self.turn_end.exists())

    def test_a_baseline_published_after_the_users_prompt_does_not_release_their_turn(self):
        # The last instant: the notification's hook is renaming its baseline into
        # place (`mv`) when the user's prompt hook runs — to its END, whatever it
        # waits for — and only then is the baseline published. It is there, and it is
        # a dead letter: the mark it names is gone.
        for shimmed in ("mv", "cat"):
            with self.subTest(the_users_prompt_lands_during=shimmed):
                self.setUp()
                self._a_turn_that_ended_without_a_write()
                self._notify_while_the_user_speaks(shimmed)
                self.assertFalse(self.turn_end.exists())
                self.tools(*["Read"] * 6)
                self.assertEqual(self.stop().returncode, 2,
                                 "the user's own turn ended on a notification's baseline")

    def test_control_with_no_user_prompt_in_between_the_notification_starts_its_turn(self):
        self._a_turn_that_ended_without_a_write()
        self.prompt(NOTIFICATIONS[0])
        self.assertEqual(self.notif_start.read_text(encoding="utf-8").split(),
                         ["0", self.turn_end.read_text(encoding="utf-8").split()[1]])
        self.tools(*["Read"] * 6)
        self.assertEqual(self.stop().returncode, 0)

    def test_the_two_exits_that_log_nothing_end_it_too(self):
        # A prompt that is empty once the IDE tags are filtered out, and the same
        # message twice within a second: the hook logs neither and — as before task
        # 088 — resets no count for them. They are still the USER's prompts: what a
        # notification began ends with them.
        for name, prompts in (
                ("empty after filtering", ["<ide_opened_file>the user opened x.py</ide_opened_file>"]),
                ("the same message twice in a second", ["say it once", "say it once"])):
            with self.subTest(name):
                self.setUp()
                self._a_turn_that_ended_without_a_write()
                if len(prompts) == 2:
                    self.prompt(prompts[0])
                    self.assertEqual(self.stop().returncode, 0)          # a reply; a new mark
                self.prompt(NOTIFICATIONS[0])
                self.assertTrue(self.notif_start.exists())
                self.prompt(prompts[-1])
                self.assertFalse(self.notif_start.exists())
                self.assertFalse(self.turn_end.exists())


class ANestedAgentsStopIsNotTheSessionsTurnEnd(_Session):
    """Post-D6 run 2. Every agent in a process chain resolves to the ROOT agent's
    session, so a `claude -p` that the session's agent runs fires this stop hook into
    the same session when it ends. Run as a background command, its stop left the
    mark, its completion notice followed with no tool call in between — and the
    notice was read as the start of a turn in the middle of the user's own. The stop
    hook marks a turn end only when the agent that stops is the session's own: one
    agent in its chain, not two."""

    def test_a_nested_agents_stop_leaves_no_mark(self):
        nested = self._nested_proc_root()
        self.prompt()
        self.tools("Bash", "Bash")                              # the user's turn has worked
        self.assertEqual(self.stop(proc_root=nested).returncode, 2)             # the nested agent's stop: held
        self.assertEqual(self.stop(active=True, proc_root=nested).returncode, 0)   # … and let through
        self.assertFalse(self.turn_end.exists(), "a nested agent's stop marked the session's turn end")
        self.prompt(NOTIFICATIONS[0])                           # its completion notice
        self.assertFalse(self.notif_start.exists())
        self.tools("Read")
        self.assertEqual(self.stop().returncode, 2, "the user's turn ended on a nested agent's notice")

    def test_control_the_sessions_own_stop_does(self):
        self.prompt()
        self.tools("Bash", "Bash")
        self.assertEqual(self.stop().returncode, 2)
        self.assertEqual(self.stop(active=True).returncode, 0)
        self.assertTrue(self.turn_end.exists())

    def test_a_nested_stop_does_not_take_away_a_mark_that_is_there(self):
        # the session's own turn ended; a nested agent that stops afterwards (a
        # leftover background one) neither renews nor removes the mark
        self.prompt()
        self.assertEqual(self.stop().returncode, 0)
        before = self.turn_end.read_text(encoding="utf-8")
        self.assertEqual(self.stop(active=True, proc_root=self._nested_proc_root()).returncode, 0)
        self.assertEqual(self.turn_end.read_text(encoding="utf-8"), before)


class AStopHookOvertakenByAUsersPrompt(_Session):
    """Post-D6 run 2, the judge's ordering: a stop hook that is still running when the
    user's next prompt arrives publishes its mark AFTER that prompt removed the old
    ones — and a notification in the user's turn would take it for a start. The mark
    carries the prompt generation the stop hook saw when it STARTED; every prompt of
    the user's begins a new one; a mark of another generation starts nothing."""

    def test_a_mark_published_after_the_users_prompt_starts_nothing(self):
        # The user's next prompt hook runs to its END while the stop hook of the turn
        # before it is still at work — at the instant it renames its mark into place
        # (`mv`), and earlier, while it is still deciding (`head`, its first read of a
        # file of the session). Either way the mark that comes out is of the
        # generation the stop hook STARTED in. (The second case is the one that tells
        # "read when it starts" from "read when it ends": a break that read the
        # generation at the end passed the first.)
        import shutil
        for shimmed in ("mv", "head"):
            with self.subTest(the_users_prompt_lands_during=shimmed):
                self.setUp()
                self.prompt()                                   # a turn with no tool call
                bindir = Path(self._tmp.name) / "shims"
                bindir.mkdir()
                done = Path(self._tmp.name) / "user-prompt-done"
                payload = Path(self._tmp.name) / "user-prompt.json"
                payload.write_text(json.dumps({"prompt": "the user speaks while the stop hook is at work"}),
                                   encoding="utf-8")
                hook = SCRIPTS / "chat-log-hook"
                (bindir / shimmed).write_text(f"""#!/bin/bash
for a in "$@"; do
    case "$a" in "{self.session_dir}"/*)
        if [ ! -e "{done}.started" ]; then
            : > "{done}.started"
            ( PATH="$PB_REAL_PATH" "{bash_or_skip()}" "{hook}" < "{payload}"; : > "{done}" ) >/dev/null 2>&1 &
            for _ in $(seq 1 160); do [ -e "{done}" ] && break; "$PB_REAL_SLEEP" 0.05; done
        fi ;;
    esac
done
exec "{shutil.which(shimmed)}" "$@"
""", encoding="utf-8")
                (bindir / shimmed).chmod(0o755)
                env = dict(os.environ, PLAYBOOK_SESSION_ID=SID, HOME=self._tmp.name,
                           PB_REAL_PATH=os.environ["PATH"], PB_REAL_SLEEP=shutil.which("sleep"),
                           PLAYBOOK_PROC_ROOT=str(self.proc_root),
                           PATH=f"{bindir}{os.pathsep}{os.environ['PATH']}")
                for k in ("BASH_ENV", "PLAYBOOK_ROLE", "PLAYBOOK_EVAL_CONFIG"):
                    env.pop(k, None)
                r = subprocess.run([bash_or_skip(), str(SCRIPTS / "stop-hook")], cwd=self.project, env=env,
                                   text=True, capture_output=True, timeout=60,
                                   input=json.dumps({"stop_hook_active": False}))
                self.assertEqual(r.returncode, 0, r.stderr)     # a chat reply: let through
                self.assertTrue(done.exists(), "the user's prompt hook never finished")
                self.assertTrue(self.turn_end.exists(),
                                "the overtaken stop hook did publish its mark — the case under test")
                self.assertEqual(self.counts(), (0, 0))
                self.prompt(NOTIFICATIONS[0])                   # in the user's turn, before any tool call
                self.assertFalse(self.notif_start.exists(),
                                 "a mark of the turn BEFORE the user's prompt was taken for a start")
                self.tools(*["Read"] * 6)
                self.assertEqual(self.stop().returncode, 2)

    def test_every_prompt_of_the_users_begins_a_new_generation(self):
        seen = []
        for text in (None, None, "<command-name>/x</command-name>",
                     "<ide_opened_file>the user opened x.py</ide_opened_file>"):
            self.prompt(text)
            seen.append(self.prompt_gen.read_text(encoding="utf-8").split()[1])
        self.assertEqual(len(set(seen)), 4, seen)
        self.prompt(NOTIFICATIONS[0])                           # … and a notification does not
        self.assertEqual(self.prompt_gen.read_text(encoding="utf-8").split()[1], seen[-1])


class AFailureWhileMarkingDoesNotChangeTheVerdict(_Session):
    """Under `set -e` a command that fails inside a plain EXIT trap replaces bash's
    exit status with 1, whatever it was (measured, bash 5.1). The mark is written
    only for an exit 0 and its writer does not fail today; this pins that the hook's
    verdict would come out unchanged if it did. The hook is run from a copy of the
    plugin whose mark writer fails — with the trap unguarded, the allowed stop
    below comes out 1."""

    def setUp(self):
        super().setUp()
        import shutil
        self.plugin_copy = Path(self._tmp.name) / "plugin"
        shutil.copytree(SCRIPTS.parent, self.plugin_copy, symlinks=True,
                        ignore=shutil.ignore_patterns("__pycache__"))
        lib = self.plugin_copy / "scripts" / "gate-echo-lib.sh"
        with open(lib, "a", encoding="utf-8") as f:
            f.write("\nwrite_session_mark() { echo 'write_session_mark: forced failure' >&2; return 1; }\n")

    def _stop_from_copy(self, active=False):
        env = dict(os.environ, PLAYBOOK_SESSION_ID=SID, HOME=self._tmp.name, PLAYBOOK_PROC_ROOT=str(self.proc_root))
        for k in ("BASH_ENV", "PLAYBOOK_ROLE", "PLAYBOOK_EVAL_CONFIG"):
            env.pop(k, None)
        return subprocess.run([bash_or_skip(), str(self.plugin_copy / "scripts" / "stop-hook")],
                              cwd=self.project, env=env, text=True, capture_output=True, timeout=60,
                              input=json.dumps({"stop_hook_active": active}))

    def test_a_blocked_stop_stays_blocked_and_an_allowed_one_allowed(self):
        self.counters_file.write_text("tools=9\nwrites=4\n", encoding="utf-8")
        r = self._stop_from_copy()
        self.assertEqual(r.returncode, 2, r.stderr)
        self.assertIn("BLOCKED: 1 unchecked gate(s)", r.stderr)
        r = self._stop_from_copy(active=True)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("forced failure", r.stderr, "the failing write was not reached — the test proves nothing")
        self.assertEqual(self.counters_file.read_text(encoding="utf-8"), "tools=9\nwrites=4\n")


class TheConsecutiveBatchGuardAcrossANotification(unittest.TestCase):
    """The same reset had a second consequence. The gate-batch guard records the
    session's tool count when it allows a batch tick and blocks the next batch unless
    another tool call ran in between; a reset in between made the difference negative,
    so a notification between two batch ticks let the second one through."""

    def _notify(self, f):
        env = dict(os.environ, PLAYBOOK_SESSION_ID=BATCH_SESSION)
        for k in ("BASH_ENV", "PLAYBOOK_ROLE"):
            env.pop(k, None)
        r = subprocess.run([bash_or_skip(), str(SCRIPTS / "chat-log-hook")], cwd=f.proj, env=env,
                           text=True, input=json.dumps({"prompt": NOTIFICATIONS[0]}),
                           capture_output=True, timeout=60)
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_a_notification_between_two_batch_ticks_does_not_free_the_second(self):
        f = ProjectFixture()
        f.set_tools_counter(10)
        r = f.run_hook(f.edit_payload(G[:2], [checked(g, NOTE) for g in G[:2]]))
        self.assertEqual(r.returncode, 0, r.stderr.decode())
        f.set_tools_counter(11)                      # the edit itself; nothing else ran
        self._notify(f)
        r = f.run_hook(f.edit_payload(G[2:4], [checked(g, NOTE) for g in G[2:4]]))
        self.assertEqual(r.returncode, 2, "the second batch went through:\n" + r.stderr.decode())


if __name__ == "__main__":
    unittest.main()
