"""An automatic notification and the stop hook's counters (owner's Q1, 2026-09-24;
PLAN S11; task 173).

The stop hook lets a turn with open gates end when the session's counters say it was
a chat reply: no write and fewer than five tool calls since the last prompt. The
chat-log hook reset those counters on EVERY prompt — also on a harness notification,
which is not the user's prompt and can land in the middle of a turn: measured on a
live session on 2026-10-10, a background command's `<task-notification>` took the
counters from `tools=20 writes=20` to `0 0` between two tool calls of one turn, so a
stop right after it was released with every gate open (task 088's finding Q1).

The owner's rule: "the stop hook's counters are no longer reset by an automatic
notification; the one exception: a turn started by a notification may exit if it made
zero writes."

These tests run the three REAL hooks as subprocesses, in the order the events happen:
`chat-log-hook` for a prompt, `state-echo-hook` for a tool call, `stop-hook` for a
stop. The rule is about an order of events; one hook alone cannot show it.
"""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

from tests._bashcheck import bash_or_skip
from tests.test_batch_close_guard import G, NOTE, ProjectFixture, checked
from tests.test_batch_close_guard import SESSION as BATCH_SESSION

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = REPO_ROOT / "plugins" / "playbook" / "scripts"
SID = "pid-notif-turn"

NOTIFICATIONS = (
    "<task-notification>\n<task-id>b1</task-id>\n<status>completed</status>\n</task-notification>",
    "[SYSTEM NOTIFICATION - NOT USER INPUT]\nThis is an automated background-task event.\n"
    "<task-notification>\n<task-id>b1</task-id>\n</task-notification>",
)
USER_COMMAND_ECHOES = (
    "<command-name>/playbook:work</command-name>\n<command-args>12</command-args>",
    "<local-command-caveat>Caveat: the messages below were generated by the user while "
    "running local commands.</local-command-caveat>",
)


class _Session(unittest.TestCase):
    """A project with one active task that has an open gate, and one session."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.project = Path(self._tmp.name) / "proj"
        task_dir = self.project / ".agent" / "tasks" / "001-x"
        task_dir.mkdir(parents=True)
        self.task_file = task_dir / "task.md"
        self.task_file.write_text(
            "# 001 - x\n\n## Status\nin_progress\n\n## Work Plan\n- [ ] a gate that is open\n",
            encoding="utf-8")
        self.session_dir = self.project / ".agent" / "sessions" / SID
        self.session_dir.mkdir(parents=True)
        (self.session_dir / "current_state").write_text("001\n", encoding="utf-8")
        self.counters_file = self.session_dir / "counters"

    def _hook(self, name, payload):
        env = dict(os.environ)
        env["PLAYBOOK_SESSION_ID"] = SID
        env["HOME"] = self._tmp.name
        for k in ("BASH_ENV", "PLAYBOOK_ROLE", "PLAYBOOK_EVAL_CONFIG"):
            env.pop(k, None)
        return subprocess.run(
            [bash_or_skip(), str(SCRIPTS / name)], cwd=self.project, env=env, text=True,
            input=json.dumps(payload), capture_output=True, timeout=60)

    # -- the events, as the harness sends them ---------------------------------------
    def prompt(self, text=None):
        if text is None:
            # each one different: the hook drops a message identical to the previous
            # one in the same second as a duplicate, before it resets anything
            self._n = getattr(self, "_n", 0) + 1
            text = f"a plain user prompt, number {self._n}"
        r = self._hook("chat-log-hook", {"prompt": text})
        self.assertEqual(r.returncode, 0, r.stderr)
        return r

    def tools(self, *names):
        for name in names:
            r = self._hook("state-echo-hook", {"tool_name": name, "tool_input": {"command": "true"}})
            self.assertEqual(r.returncode, 0, r.stderr)

    def stop(self, active=False):
        return self._hook("stop-hook", {"stop_hook_active": active})

    def counters(self) -> "dict[str, str]":
        if not self.counters_file.exists():
            return {}
        return dict(line.split("=", 1) for line in
                    self.counters_file.read_text(encoding="utf-8").splitlines() if "=" in line)

    def counts(self):
        c = self.counters()
        return int(c["tools"]), int(c["writes"])

    def a_turn_that_ended(self, writes=2):
        """A user's turn with `writes` writes that the stop hook let end: blocked once
        (open gate, real activity), then let through by its one-shot valve."""
        self.prompt()
        self.tools(*["Bash"] * writes)
        self.assertEqual(self.stop().returncode, 2)
        self.assertEqual(self.stop(active=True).returncode, 0)


class ANotificationDoesNotResetTheCounters(_Session):
    def test_an_automatic_notification_leaves_the_counts_as_they_were(self):
        for text in NOTIFICATIONS:
            with self.subTest(text[:24]):
                self.prompt()
                self.tools("Read", "Read", "Bash", "Read", "Bash")
                self.assertEqual(self.counts(), (5, 2))
                self.prompt(text)
                self.assertEqual(self.counts(), (5, 2),
                                 "a notification wiped the work count of the turn it landed in")

    def test_it_keeps_the_gate_fields_too(self):
        self.prompt()
        self.tools("Bash")
        with open(self.counters_file, "a", encoding="utf-8") as f:
            f.write("gate_x=1\n")
        self.prompt(NOTIFICATIONS[0])
        self.assertEqual(self.counters().get("gate_x"), "1")

    def test_the_echo_of_a_command_the_user_ran_still_resets(self):
        # `<command-name>` and `<local-command-caveat>` are skipped from the LOG like a
        # notification, but they are the user's act — a slash command, a `!` command —
        # and start a fresh count like any prompt of theirs.
        for text in USER_COMMAND_ECHOES:
            with self.subTest(text[:24]):
                self.prompt()
                self.tools("Read", "Bash", "Bash")
                self.prompt(text)
                self.assertEqual(self.counts(), (0, 0))

    def test_control_a_user_prompt_resets(self):
        self.prompt()
        self.tools("Read", "Bash", "Bash")
        self.prompt("and now something else")
        self.assertEqual(self.counts(), (0, 0))

    def test_with_no_counters_file_a_notification_creates_none(self):
        self.assertFalse(self.counters_file.exists())
        self.prompt(NOTIFICATIONS[0])
        self.assertFalse(self.counters_file.exists())


class AStopAfterANotification(_Session):
    def test_work_then_a_notification_in_the_middle_of_the_turn_then_a_stop_is_blocked(self):
        # What was measured live: the turn had worked, the notification landed between
        # two of its tool calls, and the stop that followed was released.
        self.prompt()
        self.tools("Bash", "Bash", "Read")
        self.prompt(NOTIFICATIONS[0])
        self.tools("Read")
        r = self.stop()
        self.assertEqual(r.returncode, 2, "released with a gate open and two writes in the turn")
        self.assertIn("BLOCKED: 1 unchecked gate(s)", r.stderr)

    def test_a_turn_a_notification_started_may_end_if_it_made_no_write(self):
        # The owner's exception. No tool-count limit in it: six read-only calls.
        self.a_turn_that_ended()
        self.prompt(NOTIFICATIONS[0])
        self.tools(*["Read"] * 6)
        r = self.stop()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_and_with_no_tool_call_at_all(self):
        self.a_turn_that_ended()
        self.prompt(NOTIFICATIONS[1])
        self.assertEqual(self.stop().returncode, 0)

    def test_one_write_in_that_turn_and_the_stop_is_blocked(self):
        for write in ("Bash", "Edit", "Write"):
            with self.subTest(write):
                self.a_turn_that_ended()
                self.prompt(NOTIFICATIONS[0])
                self.tools("Read", write)
                self.assertEqual(self.stop().returncode, 2)

    def test_a_second_notification_during_that_turn_does_not_move_the_baseline(self):
        self.a_turn_that_ended()
        self.prompt(NOTIFICATIONS[0])
        self.tools("Read", "Bash")                  # the turn has written …
        self.prompt(NOTIFICATIONS[0])               # … and another notification lands in it
        self.tools("Read")
        self.assertEqual(self.stop().returncode, 2,
                         "the second notification was taken for the start of a turn")

    def test_two_notifications_before_any_tool_call_are_one_start(self):
        self.a_turn_that_ended()
        self.prompt(NOTIFICATIONS[0])
        self.prompt(NOTIFICATIONS[1])
        self.tools("Read")
        self.assertEqual(self.stop().returncode, 0)

    def test_each_turn_a_notification_starts_is_counted_from_its_own_start(self):
        self.a_turn_that_ended()
        self.prompt(NOTIFICATIONS[0])
        self.tools("Bash")
        self.assertEqual(self.stop().returncode, 2)             # it wrote
        self.assertEqual(self.stop(active=True).returncode, 0)  # … and ended by the valve
        self.prompt(NOTIFICATIONS[0])                           # the next one starts clean
        self.tools("Read")
        self.assertEqual(self.stop().returncode, 0)

    def test_a_user_prompt_ends_what_the_notification_began(self):
        # prompt → a reply with no tool call ends (the old bypass) → a notification
        # starts a turn at zero writes → the USER speaks → six read-only calls → stop.
        # Were the notification's baseline (0) still there, this would be released.
        self.prompt()
        self.assertEqual(self.stop().returncode, 0)
        self.prompt(NOTIFICATIONS[0])
        self.prompt("now do the real thing")
        self.tools(*["Read"] * 6)
        self.assertEqual(self.stop().returncode, 2)

    def test_a_stop_that_was_blocked_is_not_the_end_of_a_turn(self):
        self.prompt()
        self.tools("Bash", "Bash")
        self.assertEqual(self.stop().returncode, 2)
        self.assertNotIn("turn_end_tools", self.counters())
        self.prompt(NOTIFICATIONS[0])                # the turn goes on after the block
        self.assertNotIn("notif_writes", self.counters())
        self.assertEqual(self.stop().returncode, 2)

    def test_a_baseline_that_is_not_a_number_releases_nothing(self):
        for junk in ("abc", "", "-0", "0x0", "9" * 30, "0 ", "$(touch pwned)"):
            with self.subTest(junk):
                self.counters_file.write_text(f"tools=9\nwrites=0\nnotif_writes={junk}\n", encoding="utf-8")
                self.assertEqual(self.stop().returncode, 2)
        self.assertFalse((self.project / "pwned").exists())

    def test_control_the_chat_reply_bypass_is_unchanged(self):
        self.prompt()
        self.tools("Read", "Read", "Read", "Read")
        self.assertEqual(self.stop().returncode, 0)             # no write, four calls
        self.prompt()
        self.tools("Read", "Read", "Read", "Read", "Read")
        self.assertEqual(self.stop().returncode, 2)             # five


class TheStopHookMarksOnlyAStopItLetThrough(_Session):
    """The mark the notification rule reads is written when the hook exits 0, and the
    hook's own verdict — its exit status, its message — comes out as before."""

    def _mark(self):
        return self.counters().get("turn_end_tools")

    def test_a_blocked_stop_leaves_no_mark_and_says_what_it_said(self):
        self.prompt()
        self.tools("Bash", "Read", "Bash")
        r = self.stop()
        self.assertEqual(r.returncode, 2)
        self.assertIn("BLOCKED: 1 unchecked gate(s) in task 001.", r.stderr)
        self.assertIn("First unchecked: a gate that is open", r.stderr)
        self.assertIsNone(self._mark())

    def test_each_way_a_stop_is_let_through_leaves_the_mark(self):
        def valve():
            self.assertEqual(self.stop().returncode, 2)
            return self.stop(active=True)

        def all_gates_done():
            self.task_file.write_text(self.task_file.read_text(encoding="utf-8").replace("- [ ]", "- [x]"),
                                      encoding="utf-8")
            return self.stop()

        def blocked_status():
            self.task_file.write_text(self.task_file.read_text(encoding="utf-8").replace(
                "## Status\nin_progress", "## Status\nblocked"), encoding="utf-8")
            return self.stop()

        def no_active_task():
            (self.session_dir / "current_state").unlink()
            return self.stop()

        for way in (valve, all_gates_done, blocked_status, no_active_task):
            with self.subTest(way.__name__):
                self.setUp()
                self.prompt()
                self.tools("Bash", "Read", "Bash")
                r = way()
                self.assertEqual(r.returncode, 0, r.stderr)
                self.assertEqual(self._mark(), "3", "the mark is the tool count at that stop")
                self.assertEqual(self.counts(), (3, 2))

    def test_the_chat_reply_bypass_leaves_it_too(self):
        self.prompt()
        self.tools("Read")
        self.assertEqual(self.stop().returncode, 0)
        self.assertEqual(self._mark(), "1")

    def test_with_no_counters_file_nothing_is_written(self):
        self.assertEqual(self.stop().returncode, 2)             # no file = work assumed
        self.assertFalse(self.counters_file.exists())
        # … and a stop that IS let through does not create one either (the first
        # version of this test only drove the blocked stop, which marks nothing
        # anyway — a break that let the mark create the file passed it)
        self.assertEqual(self.stop(active=True).returncode, 0)
        self.assertFalse(self.counters_file.exists())
        (self.session_dir / "current_state").unlink()
        self.assertEqual(self.stop().returncode, 0)             # no active task
        self.assertFalse(self.counters_file.exists())


class AFailureWhileMarkingDoesNotChangeTheVerdict(_Session):
    """Under `set -e` a command that fails inside a plain EXIT trap replaces bash's
    exit status with 1, whatever it was (measured, bash 5.1). The mark is written
    only for an exit 0 and its writer does not fail today; this pins that the hook's
    verdict would come out unchanged if it did. The hook is run from a copy of the
    plugin whose `write_counter` fails — with the trap unguarded, the allowed stop
    below comes out 1."""

    def setUp(self):
        super().setUp()
        import shutil
        self.plugin_copy = Path(self._tmp.name) / "plugin"
        shutil.copytree(SCRIPTS.parent, self.plugin_copy, symlinks=True,
                        ignore=shutil.ignore_patterns("__pycache__"))
        lib = self.plugin_copy / "scripts" / "gate-echo-lib.sh"
        with open(lib, "a", encoding="utf-8") as f:
            f.write("\nwrite_counter() { echo 'write_counter: forced failure' >&2; return 1; }\n")

    def _stop_from_copy(self, active=False):
        env = dict(os.environ, PLAYBOOK_SESSION_ID=SID, HOME=self._tmp.name)
        for k in ("BASH_ENV", "PLAYBOOK_ROLE", "PLAYBOOK_EVAL_CONFIG"):
            env.pop(k, None)
        return subprocess.run([bash_or_skip(), str(self.plugin_copy / "scripts" / "stop-hook")],
                              cwd=self.project, env=env, text=True, capture_output=True, timeout=60,
                              input=json.dumps({"stop_hook_active": active}))

    def test_a_blocked_stop_stays_blocked_and_an_allowed_one_allowed(self):
        self.counters_file.write_text("tools=9\nwrites=4\n", encoding="utf-8")
        r = self._stop_from_copy()
        self.assertEqual(r.returncode, 2, r.stderr)
        self.assertIn("BLOCKED: 1 unchecked gate(s)", r.stderr)
        r = self._stop_from_copy(active=True)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("forced failure", r.stderr, "the failing write was not reached — the test proves nothing")
        self.assertEqual(self.counters_file.read_text(encoding="utf-8"), "tools=9\nwrites=4\n")


class TheConsecutiveBatchGuardAcrossANotification(unittest.TestCase):
    """The same reset had a second consequence. The gate-batch guard records the
    session's tool count when it allows a batch tick and blocks the next batch unless
    another tool call ran in between; a reset in between made the difference negative,
    so a notification between two batch ticks let the second one through."""

    def _notify(self, f):
        env = dict(os.environ, PLAYBOOK_SESSION_ID=BATCH_SESSION)
        for k in ("BASH_ENV", "PLAYBOOK_ROLE"):
            env.pop(k, None)
        r = subprocess.run([bash_or_skip(), str(SCRIPTS / "chat-log-hook")], cwd=f.proj, env=env,
                           text=True, input=json.dumps({"prompt": NOTIFICATIONS[0]}),
                           capture_output=True, timeout=60)
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_a_notification_between_two_batch_ticks_does_not_free_the_second(self):
        f = ProjectFixture()
        f.set_tools_counter(10)
        r = f.run_hook(f.edit_payload(G[:2], [checked(g, NOTE) for g in G[:2]]))
        self.assertEqual(r.returncode, 0, r.stderr.decode())
        f.set_tools_counter(11)                      # the edit itself; nothing else ran
        self._notify(f)
        r = f.run_hook(f.edit_payload(G[2:4], [checked(g, NOTE) for g in G[2:4]]))
        self.assertEqual(r.returncode, 2, "the second batch went through:\n" + r.stderr.decode())


if __name__ == "__main__":
    unittest.main()
